// GENERATED BY CODE! DO NOT MODIFY!
namespace Watermelon
{
	public partial class PrefsSettings
	{
		public enum Key
		{
			Vibration = 0,
			Volume = 1,
			LevelNumber = 2,
			MoneyAmount = 3,
		}
	}
}