// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Music
	{
		public AudioClip gameMusic;
		public AudioClip music_main2;
		public AudioClip exampleMusic;
		public AudioClip mainMusic4;
	}
}