// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;
		public AudioClip shoot;
		public AudioClip win;
		public AudioClip lose;
		public AudioClip complete;
		public AudioClip explostion;
		public AudioClip wallButton;
		public AudioClip scream1;
		public AudioClip scream2;
	}
}